services:
  db:
    image: postgres:16-alpine
    container_name: fromistargram_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
#      - pg_data:/var/lib/postgresql/data
       - /mnt/volume1/fromistargram/pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: fromistargram_api
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATA_ROOT: /data
      REDIS_URL: redis://redis:6379
    volumes:
      - /mnt/volume1/fromistargram/data/source:/data:ro
    ports:
      - '${API_PORT:-4000}:4000'
    command: ['node', 'dist/server.js']

  imagor:
    image: shumc/imagor:latest
    container_name: fromistargram_imagor
    environment:
      IMAGOR_SECRET: ${IMAGOR_SECRET}
      FILE_LOADER_BASE_DIR: '/data'
      FILE_STORAGE_BASE_DIR: '/data'
      DEBUG: 1
      FILE_RESULT_STORAGE_BASE_DIR: '/result'
      FILE_RESULT_STORAGE_MKDIR_PERMISSION: 0755 # optional
      FILE_RESULT_STORAGE_WRITE_PERMISSION: 0666 # optional
      HTTP_LOADER_ALLOWED_SOURCES: 'https://fromistargram.ddunddun.shop'
      PORT: 8000
      IMAGOR_UNSAFE: 0
      IMAGOR_BASE_DIR: '/data'
      IMAGOR_USE_ETAG: 'true'
      FILE_SAFE_CHARS: '--'
    volumes:
      - /mnt/volume1/fromistargram/data/source:/data:ro
      - /mnt/volume1/fromistargram/data/result:/result

  imagorvideo:
    image: shumc/imagorvideo:latest
    container_name: fromistargram_imagorvideo
    environment:
      IMAGOR_SECRET: ${IMAGOR_SECRET}
      FILE_LOADER_BASE_DIR: '/data'
      FILE_STORAGE_BASE_DIR: '/data'
      DEBUG: 0
      FILE_RESULT_STORAGE_BASE_DIR: '/result'
      FILE_RESULT_STORAGE_MKDIR_PERMISSION: 0755 # optional
      FILE_RESULT_STORAGE_WRITE_PERMISSION: 0666 # optional
      HTTP_LOADER_ALLOWED_SOURCES: 'https://fromistargram.ddunddun.shop'
      PORT: 8000
      IMAGOR_UNSAFE: 0
      IMAGOR_BASE_DIR: '/data'
      IMAGOR_USE_ETAG: 'true'
      FILE_SAFE_CHARS: '--'
    volumes:
      - /mnt/volume1/fromistargram/data/source:/data:ro
      - /mnt/volume1/fromistargram/data/result:/result

  nginx-cache:
    build:
      context: ./nginx
    container_name: fromistargram_cache
    depends_on:
      - imagor
    volumes:
      - /mnt/volume1/fromistargram/nginx_cache:/var/cache/nginx
    ports:
      - '${THUMBNAIL_PORT:-8080}:80'

  redis:
    image: redis:alpine
    container_name: fromistargram_redis
    volumes:
      - /mnt/volume1/fromistargram/redis:/data